export const money = (n) => `$${n.toLocaleString("en-US")}`;

export const categories = [
  { name: "Laptops", sticker: "laptop" },
  { name: "Keyboards", sticker: "keyboard" },
  { name: "Mouse", sticker: "mouse" },
  { name: "Headphones", sticker: "headphones" },
  { name: "Circuits", sticker: "chip" },
  { name: "RC Cars", sticker: "rc" },
  { name: "Phone Stands", sticker: "stand" },
  { name: "Phones", sticker: "phone" },
  { name: "Screens", sticker: "screen" },
  { name: "Fidget Spinners", sticker: "spinner" },
];

export const products = [
  {
    id: "1",
    name: "Hex75 Mechanical Keyboard",
    category: "Keyboards",
    sticker: "keyboard",
    price: 129,
    rating: 4.8,
    stock: 24,
    vendor: "KeyForge",
    specs: ["75% layout", "Hot-swap sockets", "Gasket mount"],
  },
  {
    id: "2",
    name: "DevBook Pro 14",
    category: "Laptops",
    sticker: "laptop",
    price: 1499,
    rating: 4.9,
    stock: 7,
    vendor: "CoreWorks",
    specs: ["32 GB RAM", "1 TB SSD", "14 inch 120Hz"],
  },
  {
    id: "3",
    name: "Glide Ergo Mouse",
    category: "Mouse",
    sticker: "mouse",
    price: 59,
    rating: 4.6,
    stock: 40,
    vendor: "KeyForge",
    specs: ["Vertical grip", "Wireless", "4000 DPI"],
  },
  {
    id: "4",
    name: "Static ANC Headphones",
    category: "Headphones",
    sticker: "headphones",
    price: 199,
    rating: 4.7,
    stock: 15,
    vendor: "WaveLab",
    specs: ["Active noise cancel", "40h battery", "USB-C"],
  },
  {
    id: "5",
    name: "ESP32 Starter Kit",
    category: "Circuits",
    sticker: "chip",
    price: 34,
    rating: 4.5,
    stock: 80,
    vendor: "BitBench",
    specs: ["ESP32 board", "Breadboard", "60 jumper wires"],
  },
  {
    id: "6",
    name: "Drift RC Car 1:16",
    category: "RC Cars",
    sticker: "rc",
    price: 89,
    rating: 4.4,
    stock: 12,
    vendor: "TurboToys",
    specs: ["4WD", "2.4GHz remote", "Brushless motor"],
  },
  {
    id: "7",
    name: "Alu Phone Stand",
    category: "Phone Stands",
    sticker: "stand",
    price: 19,
    rating: 4.3,
    stock: 120,
    vendor: "DeskCraft",
    specs: ["Aluminium", "Foldable", "Non-slip base"],
  },
  {
    id: "8",
    name: "Pixel Dev Phone",
    category: "Phones",
    sticker: "phone",
    price: 599,
    rating: 4.6,
    stock: 9,
    vendor: "CoreWorks",
    specs: ["Unlocked bootloader", "128 GB", "OLED"],
  },
  {
    id: "9",
    name: "UltraWide 34 Monitor",
    category: "Screens",
    sticker: "screen",
    price: 449,
    rating: 4.8,
    stock: 5,
    vendor: "PixelPeak",
    specs: ["34 inch", "3440x1440", "USB-C 90W"],
  },
  {
    id: "10",
    name: "Titanium Fidget Spinner",
    category: "Fidget Spinners",
    sticker: "spinner",
    price: 25,
    rating: 4.9,
    stock: 60,
    vendor: "DeskCraft",
    specs: ["Titanium", "Ceramic bearing", "4 min spin"],
  },
];

export const cartItems = [
  { id: "1", qty: 1 },
  { id: "3", qty: 2 },
  { id: "10", qty: 1 },
];

export const orders = [
  {
    id: "MH-1042",
    date: "Oct 02, 2026",
    status: "Delivered",
    step: 4,
    total: 188,
    items: [
      { id: "1", qty: 1 },
      { id: "3", qty: 1 },
    ],
  },
  {
    id: "MH-1038",
    date: "Sep 28, 2026",
    status: "Shipped",
    step: 3,
    total: 199,
    items: [{ id: "4", qty: 1 }],
  },
  {
    id: "MH-1031",
    date: "Sep 21, 2026",
    status: "Processing",
    step: 1,
    total: 468,
    items: [
      { id: "9", qty: 1 },
      { id: "7", qty: 1 },
    ],
  },
];
