[project]
name = "core-api"
version = "0.1.0"
description = "Core backend API for ProjectMarketHub, built with FastAPI."
readme = "README.md"
authors = [
    { name = "Dhruv Akbari", email = "dhruvakbari.dev@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "fastapi[standard]>=0.142.2",
]

[project.scripts]
core-api = "core_api:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"